version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VITE_APP_NAME=Lukas AI
      - SITE_URL=${SITE_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - VITE_TOSS_PAYMENTS_CLIENT_KEY=${VITE_TOSS_PAYMENTS_CLIENT_KEY}
      - VITE_GOOGLE_TAG_ID=${VITE_GOOGLE_TAG_ID}
      - VITE_CHANNEL_PLUGIN_KEY=${VITE_CHANNEL_PLUGIN_KEY}
      - VITE_SENTRY_DSN=${VITE_SENTRY_DSN}
      - SENTRY_ORG=${SENTRY_ORG}
      - SENTRY_PROJECT=${SENTRY_PROJECT}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - HCAPTCHA_SITE_KEY=${HCAPTCHA_SITE_KEY}
      - HCAPTCHA_SECRET_KEY=${HCAPTCHA_SECRET_KEY}
      - TURNSTILE_SITE_KEY=${TURNSTILE_SITE_KEY}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
      - CRON_SECRET=${CRON_SECRET}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 